# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Common Vibes Series
description: >- # this means to ignore newlines until "baseurl:"
  Common Vibes is a series about empowering women to freely express sexuality. What happens when four very different women room together? Sex. Not with each other (you wish), but they’re certainly open to exploring their own sexual antics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://commonvibesseries.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  achaltin

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  #
collections:
  cast:
  crew:
  episodes:
  announcements:

webrick:
  headers:
    Cache-Control: public, max-age=315360
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
